pipeline {
    agent any
    tools {
        maven 'Maven 3.9.11'
        jdk 'GVM 25'
    }
    environment {
        // maven
        LOCAL_REPOSITORY_LOCATION = '/var/jenkins_home/.m2/repository'
        MAVEN_ARG_MAVEN_REPO_LOCAL = "-Dmaven.repo.local=${LOCAL_REPOSITORY_LOCATION}"
        // nexus
        NEXUS_VERSION = 'nexus3'
        NEXUS_PROTOCOL = 'https'
        NEXUS_URL = 'repository.nerosec.com'
        NEXUS_REPOSITORY = 'maven-nexus-repo'
        NEXUS_CREDENTIALS_ID = 'nexus-user'
    }
    stages {
        stage('GIT CLONE') {
            steps {
                git url: 'https://github.com/emilancius/noxx.git', branch: 'master'
            }
        }
        stage('BUILD') {
            steps {
                sh "mvn ${MAVEN_ARG_MAVEN_REPO_LOCAL} -DskipTests clean install"
            }
        }
        stage('TEST') {
            steps {
                sh "mvn ${MAVEN_ARG_MAVEN_REPO_LOCAL} test"
            }
        }
        stage('PUBLISH') {
            steps {
                script {
                    def path = "${env.WORKSPACE}/nerosec/noxx"
                    def names = ['noxx-commons']
                    def groupId = sh script: 'mvn help:evaluate ${MAVEN_ARG_MAVEN_REPO_LOCAL} -Dexpression=project.groupId -q -DforceStdout'
                    def version = sh script: 'mvn help:evaluate ${MAVEN_ARG_MAVEN_REPO_LOCAL} -Dexpression=project.version -q -DforceStdout'
                    def artifacts = []
                    names.each {
                        def jar = "${path}/${it}/target/${it}-${version}.jar"
                        def pom = "${path}/${it}/pom.xml"
                        def exists = sh script: "[-f ${jar}] && echo 'TRUE' || echo 'FALSE'", returnStdout: true
                        if (exists.trim() == 'TRUE') {
                            echo "Found jar to publish: ${jar}"
                            artifacts << [artifactId: it, classifier: '', file: jar, type: 'jar']
                            artifacts << [artifactId: it, classifier: '', file: pom, type: 'pom']
                        }
                    }
                    if (!artifacts.isEmpty()) {
                        nexusArtifactUploader(
                                nexusVersion: NEXUS_VERSION,
                                protocol: NEXUS_PROTOCOL,
                                nexusUrl: NEXUS_URL,
                                credentialsId: NEXUS_CREDENTIALS_ID,
                                repository: NEXUS_REPOSITORY,
                                groupId: groupId,
                                version: version,
                                artifacts: artifacts
                        )
                    }
                }
            }
        }
    }
}