CREATE TABLE IF NOT EXISTS `ACTIONS`
(
    `ID`              VARCHAR(43)  NOT NULL,
    `NAME`            VARCHAR(255) NOT NULL,
    `DESCRIPTION`     TEXT,
    `VERSION`         LONG         NOT NULL DEFAULT 1,
    `START_STEP_ID`   VARCHAR(36)  NOT NULL,
    `CATCH_STEP_ID`   VARCHAR(36),
    `TIMEOUT_MS`      LONG         NOT NULL DEFAULT 3600000,
    `STEPS`           JSON         NOT NULL,
    `ETAG`            VARCHAR(255) NOT NULL,
    `CREATED_AT`      DATETIME     NOT NULL DEFAULT NOW(),
    `LAST_UPDATED_AT` DATETIME,

    CONSTRAINT `ACTIONS_PK` PRIMARY KEY (`ID`),
    CONSTRAINT `ACTIONS_CK_LAST_UPDATED_AT_IS_AFTER_CREATED_AT` CHECK (`LAST_UPDATED_AT` >= `CREATED_AT`),
    CONSTRAINT `ACTIONS_CK_POSITIVE_VERSION` CHECK (`VERSION` > 0),
    CONSTRAINT `ACTIONS_CK_CATCH_STEP_IS_NOT_START_STEP` CHECK (`START_STEP_ID` != `CATCH_STEP_ID`)
);